repos:
  - repo: local
    hooks:
      - id: test
        name: test
        language: system
        pass_filenames: false
        entry: docker-compose run --rm app sh -c "python manage.py test"
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.3
    hooks:
      - id: seed-isort-config
        args:
          - "--application-directories"
          - "app"
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.6.4
    hooks:
      - id: isort
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        files: \.py$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
  - repo: local
    hooks:
      - id: jupyter-nb-clear-output-sensitive-files
        name: jupyter-nb-clear-output-sensitive-files
        files: \.ipynb$
        stages: [commit]
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
