# Generated by Django 3.1.3 on 2021-05-17 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street_address", models.CharField(max_length=255)),
                ("unit_number", models.CharField(max_length=16, null=True)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("zipcode", models.CharField(max_length=16)),
                ("country", models.CharField(max_length=255)),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=8, max_digits=11, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=8, max_digits=11, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("listing_number", models.CharField(max_length=255)),
                ("date_accessed", models.DateField()),
                ("price", models.IntegerField()),
                ("details_url", models.CharField(max_length=255)),
                ("size_interior", models.CharField(max_length=255, null=True)),
                ("bedrooms", models.CharField(max_length=8)),
                (
                    "num_bathrooms",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "num_stories",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("num_units", models.IntegerField(null=True)),
                ("land_size", models.CharField(max_length=255, null=True)),
                ("frontage", models.CharField(max_length=255, null=True)),
                ("photo_link", models.CharField(max_length=255, null=True)),
                ("property_type", models.CharField(max_length=255)),
                ("building_type", models.CharField(max_length=255)),
                ("ownership_type", models.CharField(max_length=255)),
                ("parking_type", models.CharField(max_length=255, null=True)),
                ("num_parking", models.IntegerField(null=True)),
                ("description", models.TextField(null=True)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="real_estate.address",
                    ),
                ),
            ],
        ),
    ]
