---
name: Continuous Deployment
on:
  push:
    branches:
      - main
  pull_request: []
jobs:
  test:
    name: Test and lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test and lint
        run: >
          docker-compose run --rm app sh -c
          "python manage.py test && black --check --diff . && flake8"
